/* Automatically generated by po-to-tbl from gettext.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"Unknown system error", 2},
  {"%s: option `%s' is ambiguous\n", 3},
  {"%s: option `--%s' doesn't allow an argument\n", 4},
  {"%s: option `%c%s' doesn't allow an argument\n", 5},
  {"%s: option `%s' requires an argument\n", 6},
  {"%s: unrecognized option `--%s'\n", 7},
  {"%s: unrecognized option `%c%s'\n", 8},
  {"%s: illegal option -- %c\n", 9},
  {"%s: invalid option -- %c\n", 10},
  {"%s: option requires an argument -- %c\n", 11},
  {"memory exhausted", 12},
  {"missing arguments", 13},
  {"too many arguments", 14},
  {"Try `%s --help' for more information\n", 15},
  {"\
Usage: %s [-h | -v | [TEXTDOMAIN] MSGID]\n\
  -h, --help           display this help and exit\n\
  -v, --version        display version information and exit\n\
  [TEXTDOMAIN] MSGID   retrieve translated message corresponding\n\
                       to MSGID from TEXTDOMAIN\n\
\n\
If the TEXTDOMAIN parameter is not given, the domain is determined from the\n\
environment variable TEXTDOMAIN.  If the message catalog is not found in the\n\
regular directory, another location can be specified with the environment\n\
variable TEXTDOMAINDIR.\n\
Standard search directory: %s\n", 16},
  {"no input file given", 17},
  {"error while opening \"%s\" for reading", 18},
  {"error while opening \"%s\" for writing", 19},
  {"\
Usage: %s [OPTION] filename.po ...\n\
Mandatory arguments to long options are mandatory for short options too.\n\
  -a, --alignment=NUMBER   align strings to NUMBER bytes (default: %d)\n\
  -h, --help               display this help and exit\n\
  -I, --input-path=LIST    list of directories searched for input files\n\
      --no-hash            binary file will not include the hash table\n\
  -o, --output-file=FILE   specify output file name as FILE\n\
  -v, --verbose            list input file anormalies\n\
  -V, --version            output version information and exit\n\
\n\
Search path is: %s\n\
\n\
If input file is -, standard input is read.  If output file is -,\n\
output is written to standard output.\n", 20},
  {"while creating hash table", 21},
  {"error while reading \"%s\"", 22},
  {"incomplete `%s' directive at end of file", 23},
  {"syntax error: value is no quoted string", 24},
  {"end of file \"%s\" while reading string", 25},
  {"illegal control sequence", 26},
  {"end of file occured inside directive value", 27},
  {"unterminated string constant", 28},
  {"trailing garbage in line", 29},
  {"previous `msgid' directive not matched by `msgstr'", 30},
  {"domain name \"%s\" not suitable as file name: will use prefix", 31},
  {"`msgid' directive expected", 32},
  {"empty msgstr entry ignored", 33},
  {"duplicate message ID", 34},
  {"this is the location of the first definition", 35},
  {"`msgstr' directive expected", 36},
  {"syntax error: unknown directive", 37},
  {"`msgid' and `msgstr' entry does not both begin with '\\n'", 38},
  {"`msgid' and `msgstr' entry does not both end with '\\n'", 39},
  {"number of format specifications in `msgid' and `msgstr' does not match", 40},
  {"format specifications for argument %u are not the same", 41},
  {"while preparing output", 42},
  {"\
Usage: %s [OPTION] INPUTFILE ...\n\
Mandatory arguments to long options are mandatory for short options too.\n\
  -a, --extract-all              extract all strings\n\
  -c, --add-comments[=TAG]       place comment block with TAG (or those\n\
                                 preceding keyword lines) in output file\n\
  -C, --c++                      recognize C++ style comments\n\
  -d, --default-domain=NAME      use NAME.po for output (instead of messages.po)\n\
  -h, --help                     display this help and exit\n\
  -I, --input-path=LIST          list of directories searched for input files\n\
  -j, --join-existing            join messages with existing file\n\
  -k, --keyword[=WORD]           additonal keyword to be looked for (without\n\
                                 WORD means not to use default keywords)\n\
  -m, --msgstr-prefix[=STRING]   use STRING or \"\" as prefix for msgstr entries\n\
  -M, --msgstr-suffix[=STRING]   use STRING or \"\" as suffix for msgstr entries\n\
      --no-location              do not write '#: filename:line' lines\n", 43},
  {"\
  -n, --add-location             generate '#: filename:line' lines (default)\n\
      --omit-header              don't write header with `msgid \"\"' entry\n\
  -p, --output-dir=DIR           output files will be placed in directory DIR\n\
  -s, --sort-output              generate sorted output and remove duplicates\n\
      --strict                   write out strict Uniforum conforming .po file\n\
  -v, --version                  output version information and exit\n\
  -x, --exclude-file=FILE        entries from FILE are not extracted\n\
\n\
Search path for supplementary .po files is:\n\
%s\n\
\n\
If INPUTFILE is -, standard input is read.\n", 44},
  {"trailing garbage after string in call of keyword", 45},
  {"syntax error: no value", 46},
  {"string length might conflict with 1024 byte limit", 47},
  {"cannot create output file \"%s\"", 48},
  {"error while writing .po file", 49},
};

int _msg_tbl_length = 49;
