#! /bin/sh

# Test pseudo-comments containing filenames that start with a digit.

tmpfiles=""
trap 'rm -fr $tmpfiles' 1 2 3 15

tmpfiles="$tmpfiles mm-test22.pot mm-test22.po"
cat <<\EOF > mm-test22.pot
msgid ""
msgstr ""
"Project-Id-Version: GNU gettext 0.11.5\n"
"POT-Creation-Date: 2002-08-20 15:24+0200\n"
"PO-Revision-Date: 2002-12-02 07:05+0100\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: 123.c:134
#, c-format
msgid "invalid argument `%s' for `%s'"
msgstr "ungültiges Argument »%s« für »%s«"
EOF

cat <<\EOF > mm-test22.po
#: 123.c:134
#, c-format
msgid "invalid argument `%s' for `%s'"
msgstr ""
EOF

tmpfiles="$tmpfiles mm-test22.out"
: ${MSGMERGE=msgmerge}
${MSGMERGE} -q mm-test22.pot mm-test22.po -o mm-test22.out
test $? = 0 || { rm -fr $tmpfiles; exit 1; }

tmpfiles="$tmpfiles mm-test22.ok"
cat <<\EOF > mm-test22.ok
msgid ""
msgstr ""
"Project-Id-Version: GNU gettext 0.11.5\n"
"POT-Creation-Date: 2002-08-20 15:24+0200\n"
"PO-Revision-Date: 2002-12-02 07:05+0100\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: 123.c:134
#, c-format
msgid "invalid argument `%s' for `%s'"
msgstr "ungültiges Argument »%s« für »%s«"
EOF

: ${DIFF=diff}
${DIFF} mm-test22.ok mm-test22.out
result=$?

rm -fr $tmpfiles

exit $result
