#! /bin/sh

# Test handling of obsolete/untranslated messages with Java .properties syntax.

tmpfiles=""
trap 'rm -fr $tmpfiles' 1 2 3 15

tmpfiles="$tmpfiles mm-test23.in1 mm-test23.in2"
cat <<EOF > mm-test23.in1
#
# def.po
#
#: file:100
not\ existing=but with translation

#: file2:101
!not\ existing\ without\ translation=

#: file3:102
still\ existing=translation

#
# trailing comments should be removed
EOF

cat <<EOF > mm-test23.in2
#
# ref.po
#
#: file3:102
still\ existing=here is normally no comment

#: file4:10
!untranslated=

#
# trailing comments should be removed, even here
EOF

tmpfiles="$tmpfiles mm-test23.out"
: ${MSGMERGE=msgmerge}
${MSGMERGE} -q --properties-input --properties-output mm-test23.in1 mm-test23.in2 -o mm-test23.out
test $? = 0 || { rm -fr $tmpfiles; exit 1; }

tmpfiles="$tmpfiles mm-test23.ok"
cat << EOF > mm-test23.ok
#: file3:102
still\ existing=translation

#: file4:10
!untranslated=
EOF

: ${DIFF=diff}
${DIFF} mm-test23.ok mm-test23.out
result=$?

rm -fr $tmpfiles

exit $result
