#! /bin/sh

# Test compendium option with fuzziness.

tmpfiles=""
trap 'rm -fr $tmpfiles' 1 2 3 15

tmpfiles="$tmpfiles mm-test7.in1 mm-test7.com mm-test7.pot"
cat <<EOF > mm-test7.in1
#: file.c:123
msgid "1"
msgstr "1x"
EOF

cat <<EOF > mm-test7.com
#: file.c:345
msgid "one, two, three"
msgstr "1, 2, 3"
EOF

cat <<EOF > mm-test7.pot
#: file.c:123
msgid "1"
msgstr ""

#: file.c:345
msgid "one, two, three..."
msgstr ""
EOF

tmpfiles="$tmpfiles mm-test7.out"
: ${MSGMERGE=msgmerge}
${MSGMERGE} -q -C mm-test7.com mm-test7.in1 mm-test7.pot -o mm-test7.out
test $? = 0 || { rm -fr $tmpfiles; exit 1; }

tmpfiles="$tmpfiles mm-test7.ok"
cat << EOF > mm-test7.ok
#: file.c:123
msgid "1"
msgstr "1x"

#: file.c:345
#, fuzzy
msgid "one, two, three..."
msgstr "1, 2, 3"
EOF

: ${DIFF=diff}
${DIFF} mm-test7.ok mm-test7.out
result=$?

rm -fr $tmpfiles

exit $result
