#! /bin/sh

# Test of general operation with Java .properties syntax.

tmpfiles=""
trap 'rm -fr $tmpfiles' 1 2 3 15

tmpfiles="$tmpfiles mu-test4.in"
cat <<EOF > mu-test4.in
eight=eighth

five=fifth

four=fourth

one=first

seven=seventh

six=sixth

three=third

two=second
EOF

tmpfiles="$tmpfiles mu-test4.mo"
: ${MSGFMT=msgfmt}
${MSGFMT} --properties-input mu-test4.in -o mu-test4.mo
test $? = 0 || { rm -fr $tmpfiles; exit 1; }

tmpfiles="$tmpfiles mu-test4.out"
: ${MSGUNFMT=msgunfmt}
${MSGUNFMT} --properties-output mu-test4.mo -o mu-test4.out
test $? = 0 || { rm -fr $tmpfiles; exit 1; }

: ${DIFF=diff}
${DIFF} mu-test4.in mu-test4.out
result=$?

rm -fr $tmpfiles

exit $result
