#!/bin/sh
. "${srcdir=.}/init.sh"; path_prepend_ . ../src

# Test of Tcl support: escape sequences with unpaired surrogates.

cat <<\EOF > xg-t-5a.tcl
puts [_ "\uD83D"]
EOF

cat <<\EOF > xg-t-5b.tcl
puts [_ "\udc1c"]
EOF

: ${XGETTEXT=xgettext}
LANGUAGE= LC_ALL=C ${XGETTEXT} --no-location -k_ -d xg-t-5.tmp xg-t-5a.tcl 2>xg-t-5.err
result=$?
cat xg-t-5.err
test $result = 0 || Exit 1

: ${XGETTEXT=xgettext}
LANGUAGE= LC_ALL=C ${XGETTEXT} --no-location -k_ -d xg-t-5.tmp xg-t-5b.tcl 2>xg-t-5.err
result=$?
cat xg-t-5.err
test $result = 0 || Exit 1

exit 0
