#! /bin/sh
. "${srcdir=.}/init.sh"; path_prepend_ . ../src

# Test C support: non-ASCII extracted comments.

: ${XGETTEXT=xgettext}

${XGETTEXT} --from-code=ISO-8859-1 --add-comments --no-location --no-wrap \
            -o xg-c-24.tmp "$abs_srcdir"/xg-c-24.c || Exit 1
grep -v 'POT-Creation-Date' < xg-c-24.tmp > xg-c-24.tmq || Exit 1
LC_ALL=C tr -d '\r' < xg-c-24.tmq > xg-c-24.po || Exit 1

cat <<\EOF > xg-c-24.ok
# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

#. A mountain near Zürich.
msgid "Käferberg"
msgstr ""
EOF

: ${DIFF=diff}
${DIFF} xg-c-24.ok xg-c-24.po || Exit 1
