#!/bin/sh
#
# Some tests for java plural keyword support
#

tmpfiles=""
trap 'rm -fr $tmpfiles' 1 2 3 15

tmpfiles="$tmpfiles xg-test15.java"
cat <<EOF > xg-test15.java
class TestCase {
    public TestCase() {
        Bundle test = Bundle.getBundle();
        test.ngettext("test 1", "plural test");
    }
}
EOF

tmpfiles="$tmpfiles xg-test15.po"
: ${XGETTEXT=xgettext}
${XGETTEXT} --omit-header --no-location -d xg-test15 xg-test15.java
test $? = 0 || { rm -fr $tmpfiles; exit 1; }

tmpfiles="$tmpfiles xg-test15.ok"
cat <<EOF > xg-test15.ok
msgid "test 1"
msgid_plural "plural test"
msgstr[0] ""
msgstr[1] ""
EOF

: ${DIFF=diff}
${DIFF} xg-test15.ok xg-test15.po
result=$?

rm -fr $tmpfiles

exit $result
