#! /bin/sh

tmpfiles=""
trap 'rm -fr $tmpfiles' 1 2 3 15

tmpfiles="$tmpfiles xg-test7.in.C"
cat <<EOF > xg-test7.in.C
/* This comment will not be extracted.  */
gettext ("help");

/*   XXX: But this one will.  */
gettext_noop ("me");

//XXX: ..and this
dcgettext ("foo", "quick", LC_MESSAGES);

  /* not not not */
dgettext ("bar", "!");
EOF

tmpfiles="$tmpfiles xg-test7.po"
: ${XGETTEXT=xgettext}
${XGETTEXT} --omit-header --no-location --add-comments=XXX xg-test7.in.C \
  -d xg-test7
test $? = 0 || { rm -fr $tmpfiles; exit 1; }

tmpfiles="$tmpfiles xg-test7.ok"
cat <<EOF > xg-test7.ok
msgid "help"
msgstr ""

#. XXX: But this one will.
msgid "me"
msgstr ""

#. XXX: ..and this
msgid "quick"
msgstr ""

msgid "!"
msgstr ""
EOF

: ${DIFF=diff}
${DIFF} xg-test7.ok xg-test7.po
result=$?

rm -fr $tmpfiles

exit $result
