#! /bin/sh

# Test C, C++, JavaProperties extractors.

tmpfiles=""
trap 'rm -fr $tmpfiles' 1 2 3 15

tmpfiles="$tmpfiles xg-test24.in.properties xg-test24.c xg-test24.cc"
cat <<EOF > xg-test24.in.properties
#: file1.c:199
#, fuzzy
!extract\ me=some text to get fuzzy copied to result

#: file2.cc:200
!what\ about\ me=

#: file3.c:10
#, c-format, fuzzy
!hello=Again some text for fuzzy
EOF

cat <<EOF > xg-test24.c
#include <libintl.h>
#include <stdio.h>
int
main (int argc, char *argv[])
{
  printf (dcgettext ("hello", "Hello, world."));
  return 0;
}
EOF

cat <<EOF > xg-test24.cc
#include <iostream.h>
#include <libintl.h>
#include <locale.h>
int
main (int argc, char *argv[])
{
  cout << dcgettext ("hello", "Hello world!", LC_MESSAGES) << endl;
  return 0;
}
EOF

tmpfiles="$tmpfiles xg-test24.po"
: ${XGETTEXT=xgettext}
${XGETTEXT} --omit-header -n xg-test24.in.properties \
  xg-test24.c xg-test24.cc -d xg-test24
test $? = 0 || { rm -fr $tmpfiles; exit 1; }

tmpfiles="$tmpfiles xg-test24.ok"
cat <<EOF > xg-test24.ok
#: file1.c:199
#, fuzzy
msgid "extract me"
msgstr "some text to get fuzzy copied to result"

#: file2.cc:200
msgid "what about me"
msgstr ""

#: file3.c:10
#, fuzzy, c-format
msgid "hello"
msgstr "Again some text for fuzzy"

#: xg-test24.c:6
msgid "Hello, world."
msgstr ""

#: xg-test24.cc:7
msgid "Hello world!"
msgstr ""
EOF

: ${DIFF=diff}
${DIFF} xg-test24.ok xg-test24.po
result=$?

rm -fr $tmpfiles

exit $result
