#! /bin/sh

# Even an empty string is extracted, if not overridden by xgettext's
# default-constructed header entry.

tmpfiles=""
trap 'rm -fr $tmpfiles' 1 2 3 15

tmpfiles="$tmpfiles xg-test12.in.c"
cat <<EOF > xg-test12.in.c
This is a test of the xgettext functionality.
/* xgettext:no-c-format */
_("extract me")
Sometimes keywords can be spread apart
xgettext:no-c-format
_ ( "what about me" )
And even further on occasion
_
(
"hello"
)

/* also empty strings */
_("")
EOF

tmpfiles="$tmpfiles xg-test12.po"
: ${XGETTEXT=xgettext}
${XGETTEXT} -d xg-test12 -k_ --omit-header --no-location xg-test12.in.c
test $? = 0 || { rm -fr $tmpfiles; exit 1; }

tmpfiles="$tmpfiles xg-test12.ok"
cat <<EOF > xg-test12.ok
#, no-c-format
msgid "extract me"
msgstr ""

msgid "what about me"
msgstr ""

msgid "hello"
msgstr ""

msgid ""
msgstr ""
EOF

: ${DIFF=diff}
${DIFF} xg-test12.ok xg-test12.po
result=$?

rm -fr $tmpfiles

exit $result
