#!/bin/sh

# Test of Tcl support.

tmpfiles=""
trap 'rm -fr $tmpfiles' 1 2 3 15

tmpfiles="$tmpfiles xg-test21.tcl"
cat <<\EOF > xg-test21.tcl
#!/usr/bin/tclsh

proc isValid {target} {
	global viScreenId
	set address [valid $target]
	# This comment is not extracted.
	if {$address != 0} {
		# First comment line.

		# Second comment line.
		viMsg $viScreenId [format [_ "%s is %s"] $target [string trim $address]]
	} else {
		viMsg $viScreenId [format [_ "%s not found"] $target]
	}
}
EOF

tmpfiles="$tmpfiles xg-test21.err xg-test21.tmp xg-test21.pot"
: ${XGETTEXT=xgettext}
${XGETTEXT} --add-comments --no-location -k_ -o xg-test21.tmp xg-test21.tcl 2>xg-test21.err
test $? = 0 || { cat xg-test21.err; rm -fr $tmpfiles; exit 1; }
grep -v 'POT-Creation-Date' < xg-test21.tmp > xg-test21.pot

tmpfiles="$tmpfiles xg-test21.ok"
cat <<\EOF > xg-test21.ok
# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=CHARSET\n"
"Content-Transfer-Encoding: 8bit\n"

#. First comment line.
#. Second comment line.
#, tcl-format
msgid "%s is %s"
msgstr ""

#, tcl-format
msgid "%s not found"
msgstr ""
EOF

: ${DIFF=diff}
${DIFF} xg-test21.ok xg-test21.pot
result=$?

rm -fr $tmpfiles

exit $result
