#!/bin/sh

tmpfiles=""
trap 'rm -fr $tmpfiles' 1 2 3 15

tmpfiles="$tmpfiles out"
TERM=xterm ./test-term-ostream > out

: ${DIFF=diff}
${DIFF} ${srcdir}/test-term-ostream-xterm.out out > /dev/null
result=$?

rm -fr $tmpfiles

exit $result
