#! /bin/sh

trap 'rm -fr $tmpfiles' 1 2 3 15

tmpfiles="mf-test3.po"
cat <<EOF >mf-test3.po
#
#       xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
#       xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
#       xxxxxxxxxxxxxxxxxxxx
#
#       xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
#       xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
#       xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
#       xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
msgid   ""
msgstr  ""
EOF

tmpfiles="$tmpfiles mftest3.mo"
: ${MSGFMT=msgfmt}
LC_MESSAGES=C LC_ALL= \
${MSGFMT} mf-test3.po -o mftest3.mo 2>&1 \
  | grep -v 'warning: Charset' | grep -v '^ '

test ! -f mftest3.mo
result=$?

rm -fr $tmpfiles

exit $result
