#! /bin/sh

# Test --update: nothing changed; don't normalize second message

tmpfiles=""
trap 'rm -fr $tmpfiles' 1 2 3 15

tmpfiles="$tmpfiles mm-test14.po"
cat <<\EOF > mm-test14.po
# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR Free Software Foundation, Inc.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
msgid ""
msgstr ""
"Project-Id-Version: cog_training 1.0\n"
"POT-Creation-Date: 2001-04-29 22:40+0200\n"
"PO-Revision-Date: 2001-04-29 21:19+02:00\n"
"Last-Translator: Felix N. <xyz@zyx.uucp>\n"
"Language-Team: German <de@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=ISO-8859-1\n"
"Content-Transfer-Encoding: 8bit\n"

#: cogarithmetic.cc:12
msgid "white"
msgstr "weiﬂ"

# stay away from normalizing
#: cogarithmetic.cc:12
msgid "black"
msgstr ""
"schwarz"
EOF

tmpfiles="$tmpfiles mm-test14.pot"
cat <<EOF > mm-test14.pot
# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR Free Software Foundation, Inc.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"POT-Creation-Date: 2001-04-29 22:40+0200\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=ISO-8859-1\n"
"Content-Transfer-Encoding: 8bit\n"

#: cogarithmetic.cc:12
msgid "white"
msgstr ""

#: cogarithmetic.cc:12
msgid "black"
msgstr ""
EOF

tmpfiles="$tmpfiles mm-test14.bak"
cp mm-test14.po mm-test14.bak

tmpfiles="$tmpfiles mm-test14.po~"
: ${MSGMERGE=msgmerge}
${MSGMERGE} -q --update mm-test14.po mm-test14.pot
test $? = 0 || { rm -fr $tmpfiles; exit 1; }

: ${DIFF=diff}
${DIFF} mm-test14.bak mm-test14.po
result=$?

rm -fr $tmpfiles

exit $result
