#! /bin/sh

# Duplicates are also fatal in obsolete marked entries (cf. msgmerge-3).

tmpfiles=""
trap 'rm -fr $tmpfiles' 1 2 3 15

tmpfiles="$tmpfiles mm-test13.in1 mm-test13.in2"
cat <<EOF > mm-test13.in1
msgid "2" msgstr "2"
msgid "3" msgstr "3"
#~ msgid
#~ "2"
#~ msgstr
#~ "ha ha"
EOF

cat <<EOF > mm-test13.in2
msgid "1" msgstr ""
msgid "2" msgstr ""
msgid "3" msgstr ""
EOF

tmpfiles="$tmpfiles mm-test13.err"
: ${MSGMERGE=msgmerge}
LC_MESSAGES=C LC_ALL= \
${MSGMERGE} -q mm-test13.in1 mm-test13.in2 -o /dev/null \
    2> mm-test13.err

tmpfiles="$tmpfiles mm-test13.ok"
cat << EOF > mm-test13.ok
mm-test13.in1:3: duplicate message definition
mm-test13.in1:1: ...this is the location of the first definition
msgmerge: found 1 fatal error
EOF

: ${DIFF=diff}
${DIFF} mm-test13.ok mm-test13.err
result=$?

rm -fr $tmpfiles

exit $result
