#! /bin/sh

tmpfiles=""
trap 'rm -fr $tmpfiles' 1 2 3 15

tmpfiles="$tmpfiles msguniq-1.out"
: ${MSGUNIQ-msguniq}
${MSGUNIQ} -w 1000 ${top_srcdir}/tests/msguniq-a.in -o msguniq-1.out

: ${DIFF=diff}
${DIFF} ${top_srcdir}/tests/msguniq-a.out msguniq-1.out
result=$?

rm -fr $tmpfiles

exit $result
