#! /bin/sh

tmpfiles=""
trap 'rm -fr $tmpfiles' 1 2 3 15

tmpfiles="$tmpfiles muniq-1.out"
: ${MSGUNIQ-msguniq}
${MSGUNIQ} -w 1000 ${top_srcdir}/tests/msguniq-1.in -o muniq-1.out

: ${DIFF=diff}
${DIFF} ${top_srcdir}/tests/msguniq-1.out muniq-1.out
result=$?

rm -fr $tmpfiles

exit $result
