#!/bin/sh

# Test config.rpath and AC_LIB_LINKFLAGS macro.
# With dependencies: a shared library depending on a shared library,
# and a static library depending on both.

rp=rp3aad
build1_configure_flags=
build2_configure_flags=
build3_configure_flags=--disable-shared
build4_package=rpathlz
remove_la=no

. $top_srcdir/tests/rpath-3_a
