#! /bin/sh

# Test recognition of ISO C 99 <inttypes.h> format string directives.

tmpfiles=""
trap 'rm -fr $tmpfiles' 1 2 3 15

tmpfiles="$tmpfiles xg-test22.c"
cat <<EOF > xg-test22.c
void foo ()
{
  printf (_("File size is: %" PRId64), size);
  printf (_("File age is %10" PRIdMAX " microseconds"), age);
  printf (_(PRIXFAST16 " errors"), nerrs);
  printf (_(PRIXFAT16 " mistakes"), nerrs);
}
EOF

tmpfiles="$tmpfiles xg-test22.po"
: ${XGETTEXT=xgettext}
${XGETTEXT} --omit-header --no-location -k_ -o xg-test22.po xg-test22.c
test $? = 0 || { rm -fr $tmpfiles; exit 1; }

tmpfiles="$tmpfiles xg-test22.ok"
cat <<EOF > xg-test22.ok
#, c-format
msgid "File size is: %<PRId64>"
msgstr ""

#, c-format
msgid "File age is %10<PRIdMAX> microseconds"
msgstr ""

msgid "<PRIXFAST16> errors"
msgstr ""

msgid " mistakes"
msgstr ""
EOF

: ${DIFF=diff}
${DIFF} xg-test22.ok xg-test22.po
result=$?

rm -fr $tmpfiles

exit $result
