#! /bin/sh
# One argument is required which is the path to the toplevel directory
# of the distribution.

trap 'rm -fr $tmpfiles' 1 2 3 15

tmpfiles="xg-test1.po"
: ${XGETTEXT=xgettext}
${XGETTEXT} -d xg-test1 -k_ --omit-header \
 $top_srcdir/src/xgettext.c $top_srcdir/src/msgfmt.c $top_srcdir/src/gettext.c

: ${DIFF=diff}
${DIFF} $top_srcdir/tests/xg-test1.ok.po xg-test1.po
result=$?

rm -fr $tmpfiles

exit $result
