#! /bin/sh

tmpfiles=""
trap 'rm -fr $tmpfiles' 1 2 3 15

tmpfiles="$tmpfiles xg-test6.in.cc"
cat <<EOF > xg-test6.in.cc
main(){printf(gettext/*puke*/(/*barf*/"Hello, " "World!" "\n")); }
EOF

tmpfiles="$tmpfiles xg-test6.po"
: ${XGETTEXT=xgettext}
${XGETTEXT} --omit-header --no-location --add-comments xg-test6.in.cc -d xg-test6
test $? = 0 || { rm -fr $tmpfiles; exit 1; }

tmpfiles="$tmpfiles xg-test6.ok"
cat <<EOF > xg-test6.ok
#. puke
#. barf
msgid "Hello, World!\n"
msgstr ""
EOF

: ${DIFF=diff}
${DIFF} xg-test6.ok xg-test6.po
result=$?

rm -fr $tmpfiles

exit $result
