#! /bin/sh

trap 'rm -fr $tmpfiles' 1 2 3 15

tmpfiles="$tmpfiles xg-test5.in.c"
cat <<EOF > xg-test5.in.c
main()??<printf(gettext("Hello, " "World!" "??/n")); ??>
EOF

tmpfiles="$tmpfiles xg-test5.po"
: ${XGETTEXT=xgettext}
${XGETTEXT} --omit-header --trigraphs xg-test5.in.c -d xg-test5

tmpfiles="$tmpfiles xg-test5.ok"
cat <<EOF > xg-test5.ok
msgid "Hello, World!\n"
msgstr ""
EOF

: ${DIFF=diff}
${DIFF} xg-test5.ok xg-test5.po
result=$?

rm -fr $tmpfiles

exit $result
