#!/bin/sh
#
# Some tests for java plural keyword support
#

tmpfiles=""
trap 'rm -fr $tmpfiles' 1 2 3 15

tmpfiles="$tmpfiles xg-test16.java"
cat <<EOF > xg-test16.java
class TestCase {
    public TestCase() {
        Bundle test = Bundle.getBundle();
        test.ngettext(test, "test 1", "plural test");
    }
}
EOF

tmpfiles="$tmpfiles xg-test16.po"
: ${XGETTEXT=xgettext}
${XGETTEXT} --omit-header --no-location --keyword=ngettext:2,3 -d xg-test16 xg-test16.java
test $? = 0 || { rm -fr $tmpfiles; exit 1; }

tmpfiles="$tmpfiles xg-test16.ok"
cat <<EOF > xg-test16.ok
msgid "test 1"
msgid_plural "plural test"
msgstr[0] ""
msgstr[1] ""
EOF

: ${DIFF=diff}
${DIFF} xg-test16.ok xg-test16.po
result=$?

rm -fr $tmpfiles

exit $result
