/* List of exported symbols of libgettextsrc on Cygwin.
   Copyright (C) 2006 Free Software Foundation, Inc.
   Written by Bruno Haible <bruno@clisp.org>, 2006.

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 2, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software Foundation,
   Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.  */

#include "cygwin/export.h"

VARIABLE(allow_duplicates)
VARIABLE(format_language)
VARIABLE(format_language_pretty)
VARIABLE(formatstring_awk)
VARIABLE(formatstring_boost)
VARIABLE(formatstring_c)
VARIABLE(formatstring_csharp)
VARIABLE(formatstring_elisp)
VARIABLE(formatstring_gcc_internal)
VARIABLE(formatstring_java)
VARIABLE(formatstring_librep)
VARIABLE(formatstring_lisp)
VARIABLE(formatstring_objc)
VARIABLE(formatstring_parsers)
VARIABLE(formatstring_pascal)
VARIABLE(formatstring_perl)
VARIABLE(formatstring_perl_brace)
VARIABLE(formatstring_php)
VARIABLE(formatstring_python)
VARIABLE(formatstring_qt)
VARIABLE(formatstring_scheme)
VARIABLE(formatstring_sh)
VARIABLE(formatstring_smalltalk)
VARIABLE(formatstring_tcl)
VARIABLE(formatstring_ycp)
VARIABLE(gram_max_allowed_errors)
VARIABLE(gram_pos)
VARIABLE(input_syntax)
VARIABLE(less_than)
VARIABLE(line_comment)
VARIABLE(more_than)
VARIABLE(msgcomm_mode)
VARIABLE(omit_header)
VARIABLE(pass_obsolete_entries)
VARIABLE(plural_table)
VARIABLE(plural_table_size)
VARIABLE(po_charset_ascii)
VARIABLE(po_charset_utf8)
VARIABLE(po_error)
VARIABLE(po_error_at_line)
VARIABLE(po_gram_lval)
VARIABLE(po_lex_charset)
VARIABLE(po_lex_iconv)
VARIABLE(po_lex_weird_cjk)
VARIABLE(po_multiline_error)
VARIABLE(po_multiline_warning)
VARIABLE(po_xerror)
VARIABLE(po_xerror2)
VARIABLE(use_first)

#if 0 /* not needed - we use --export-all-symbols */
FUNCTION(catenate_msgdomain_list)
FUNCTION(check_message)
FUNCTION(check_message_list)
FUNCTION(check_msgid_msgstr_format)
FUNCTION(compare_po_locale_charsets)
FUNCTION(convert_string)
FUNCTION(default_add_message)
FUNCTION(default_comment)
FUNCTION(default_comment_dot)
FUNCTION(default_comment_filepos)
FUNCTION(default_comment_special)
FUNCTION(default_constructor)
FUNCTION(default_destructor)
FUNCTION(default_directive_domain)
FUNCTION(default_directive_message)
FUNCTION(default_parse_brief)
FUNCTION(default_parse_debrief)
FUNCTION(default_po_reader_alloc)
FUNCTION(default_set_domain)
FUNCTION(dir_list_append)
FUNCTION(dir_list_nth)
FUNCTION(dir_list_restore)
FUNCTION(dir_list_save_reset)
FUNCTION(extract_plural_expression)
FUNCTION(fuzzy_search_goal_function)
FUNCTION(get_python_format_unnamed_arg_count)
FUNCTION(get_sysdep_c_format_directives)
FUNCTION(iconv_message_list)
FUNCTION(iconv_msgdomain_list)
FUNCTION(is_ascii_message_list)
FUNCTION(is_ascii_msgdomain_list)
FUNCTION(is_ascii_string)
FUNCTION(message_alloc)
FUNCTION(message_comment_append)
FUNCTION(message_comment_dot_append)
FUNCTION(message_comment_filepos)
FUNCTION(message_copy)
FUNCTION(message_list_alloc)
FUNCTION(message_list_append)
FUNCTION(message_list_free)
FUNCTION(message_list_insert_at)
FUNCTION(message_list_list_alloc)
FUNCTION(message_list_list_append)
FUNCTION(message_list_list_append_list)
FUNCTION(message_list_list_free)
FUNCTION(message_list_list_search)
FUNCTION(message_list_prepend)
FUNCTION(message_list_remove_if_not)
FUNCTION(message_list_search)
FUNCTION(message_list_search_fuzzy)
FUNCTION(message_page_width_ignore)
FUNCTION(message_page_width_set)
FUNCTION(message_print_style_escape)
FUNCTION(message_print_style_indent)
FUNCTION(message_print_style_uniforum)
FUNCTION(message_print_syntax_properties)
FUNCTION(message_print_syntax_stringtable)
FUNCTION(msgdomain_list_alloc)
FUNCTION(msgdomain_list_english)
FUNCTION(msgdomain_list_equal)
FUNCTION(msgdomain_list_free)
FUNCTION(msgdomain_list_print)
FUNCTION(msgdomain_list_sort_by_filepos)
FUNCTION(msgdomain_list_sort_by_msgid)
FUNCTION(msgdomain_list_sublist)
FUNCTION(open_po_file)
FUNCTION(possible_format_p)
FUNCTION(po_charset_canonicalize)
FUNCTION(po_charset_character_iterator)
FUNCTION(po_gram_error_at_line)
FUNCTION(po_lex_pass_obsolete_entries)
FUNCTION(po_parse_comment_special)
FUNCTION(po_reader_alloc)
FUNCTION(po_reader_free)
FUNCTION(po_scan)
FUNCTION(po_strftime)
FUNCTION(read_names_from_file)
FUNCTION(read_po)
FUNCTION(read_po_file)
FUNCTION(string_list_alloc)
FUNCTION(string_list_append)
FUNCTION(string_list_append_unique)
FUNCTION(string_list_destroy)
FUNCTION(string_list_free)
FUNCTION(string_list_init)
FUNCTION(string_list_join)
FUNCTION(string_list_member)
FUNCTION(textmode_xerror)
FUNCTION(textmode_xerror2)
#endif
